/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PersonIdImport } from './routes/$personId'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const PersonIdRoute = PersonIdImport.update({
  id: '/$personId',
  path: '/$personId',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$personId': {
      id: '/$personId'
      path: '/$personId'
      fullPath: '/$personId'
      preLoaderRoute: typeof PersonIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$personId': typeof PersonIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$personId': typeof PersonIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$personId': typeof PersonIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$personId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$personId'
  id: '__root__' | '/' | '/$personId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PersonIdRoute: typeof PersonIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PersonIdRoute: PersonIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$personId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$personId": {
      "filePath": "$personId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
